-- -- SQL for tables shown in the second pasted image
-- -- MySQL / MariaDB (phpMyAdmin)

-- CREATE TABLE IF NOT EXISTS `users` (
--   `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
--   `name` VARCHAR(255) NOT NULL,
--   `email` VARCHAR(255) NOT NULL,
--   `email_verified_at` TIMESTAMP NULL DEFAULT NULL,
--   `password` VARCHAR(255) NOT NULL,
--   `remember_token` VARCHAR(100) NULL DEFAULT NULL,
--   `created_at` TIMESTAMP NULL DEFAULT NULL,
--   `updated_at` TIMESTAMP NULL DEFAULT NULL,
--   PRIMARY KEY (`id`),
--   UNIQUE KEY `users_email_unique` (`email`)
-- ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- CREATE TABLE IF NOT EXISTS `password_reset_tokens` (
--   `email` VARCHAR(255) NOT NULL,
--   `token` VARCHAR(255) NOT NULL,
--   `created_at` TIMESTAMP NULL DEFAULT NULL,
--   PRIMARY KEY (`email`)
-- ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- CREATE TABLE IF NOT EXISTS `sessions` (
--   `id` VARCHAR(255) NOT NULL,
--   `user_id` BIGINT UNSIGNED NULL,
--   `ip_address` VARCHAR(45) NULL,
--   `user_agent` TEXT NULL,
--   `payload` LONGTEXT NOT NULL,
--   `last_activity` INT NOT NULL,
--   PRIMARY KEY (`id`),
--   KEY `sessions_user_id_index` (`user_id`),
--   KEY `sessions_last_activity_index` (`last_activity`)
-- ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- CREATE TABLE IF NOT EXISTS `cache` (
--   `key` VARCHAR(255) NOT NULL,
--   `value` MEDIUMTEXT NOT NULL,
--   `expiration` INT NOT NULL,
--   PRIMARY KEY (`key`)
-- ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- CREATE TABLE IF NOT EXISTS `cache_locks` (
--   `key` VARCHAR(255) NOT NULL,
--   `owner` VARCHAR(255) NOT NULL,
--   `expiration` INT NOT NULL,
--   PRIMARY KEY (`key`)
-- ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- CREATE TABLE IF NOT EXISTS `jobs` (
--   `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
--   `queue` VARCHAR(255) NOT NULL,
--   `payload` LONGTEXT NOT NULL,
--   `attempts` TINYINT UNSIGNED NOT NULL,
--   `reserved_at` INT UNSIGNED NULL,
--   `available_at` INT UNSIGNED NOT NULL,
--   `created_at` INT UNSIGNED NOT NULL,
--   PRIMARY KEY (`id`),
--   KEY `jobs_queue_index` (`queue`)
-- ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- CREATE TABLE IF NOT EXISTS `job_batches` (
--   `id` VARCHAR(255) NOT NULL,
--   `name` VARCHAR(255) NOT NULL,
--   `total_jobs` INT NOT NULL,
--   `pending_jobs` INT NOT NULL,
--   `failed_jobs` INT NOT NULL,
--   `failed_job_ids` LONGTEXT NOT NULL,
--   `options` MEDIUMTEXT NULL,
--   `cancelled_at` INT NULL,
--   `created_at` INT NOT NULL,
--   `finished_at` INT NULL,
--   PRIMARY KEY (`id`)
-- ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- CREATE TABLE IF NOT EXISTS `failed_jobs` (
--   `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
--   `uuid` VARCHAR(255) NOT NULL,
--   `connection` TEXT NOT NULL,
--   `queue` TEXT NOT NULL,
--   `payload` LONGTEXT NOT NULL,
--   `exception` LONGTEXT NOT NULL,
--   `failed_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
--   PRIMARY KEY (`id`),
--   UNIQUE KEY `failed_jobs_uuid_unique` (`uuid`)
-- ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- CREATE TABLE IF NOT EXISTS `migrations` (
--   `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
--   `migration` VARCHAR(255) NOT NULL,
--   `batch` INT NOT NULL,
--   PRIMARY KEY (`id`)
-- ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- CREATE TABLE IF NOT EXISTS `degrees` (
--   `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
--   `title` VARCHAR(255) NOT NULL,
--   `created_at` TIMESTAMP NULL DEFAULT NULL,
--   `updated_at` TIMESTAMP NULL DEFAULT NULL,
--   PRIMARY KEY (`id`),
--   UNIQUE KEY `degrees_title_unique` (`title`)
-- ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- CREATE TABLE `profiles` (
--   `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
--   `user_id` BIGINT UNSIGNED NOT NULL,
--   `bio` VARCHAR(50) NULL,
--   `avatar` VARCHAR(50) NULL,
--   `created_at` TIMESTAMP NULL DEFAULT NULL,
--   `updated_at` TIMESTAMP NULL DEFAULT NULL,
--   PRIMARY KEY (`id`),
--   INDEX `profiles_user_id_index` (`user_id`),
--   CONSTRAINT `profiles_user_id_foreign`
--     FOREIGN KEY (`user_id`) REFERENCES `users`(`id`)
--     ON DELETE CASCADE
-- ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


-- CREATE TABLE IF NOT EXISTS `students` (
--   `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
--   `fname` VARCHAR(255) NOT NULL,
--   `mname` VARCHAR(255) NOT NULL,
--   `lname` VARCHAR(255) NOT NULL,
--   `email` VARCHAR(255) NOT NULL,
--   `contact_no` VARCHAR(255) NOT NULL,
--   `age` INT NULL,
--   `course` VARCHAR(255) NULL,
--   `degree_id` BIGINT UNSIGNED NULL,
--   `password` VARCHAR(255) NULL,
--   `created_at` TIMESTAMP NULL DEFAULT NULL,
--   `updated_at` TIMESTAMP NULL DEFAULT NULL,
--   PRIMARY KEY (`id`),
--   KEY `students_degree_id_index` (`degree_id`),
--   CONSTRAINT `students_degree_id_foreign` FOREIGN KEY (`degree_id`) REFERENCES `degrees` (`id`) ON DELETE SET NULL
-- ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;